### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by DMailMan** [ActianCorp/SC930_Tools#1]
I'm running the tool over a bunch of SC930 output files (106 in total), using the GUI display, and although I can get the LRQ data, the results are not presented in sorted order. 

Is the Sort option supposed to work in the GUI display, or only from the command-line ? It would be equally handy in the GUI to present the results in ascending or descending order, and this is implied by the checkbox on 'Sort Results'.

**Comment by maspa05** [comment]
Looks like the version I imported was one that was one that was a work-in-progress I was doing for Keith B. The sorting works but it's on beginning timestamp rather than query length. This was because Keith was looking at multiple files and wanted to see the queries in overall order. The idea was to eventually have the sort by criteria as an option but in the meantime I hard-coded it. 

Anyway I'll revert this to other version when I get a minute.

**Comment by maspa05** [comment]
Closed by cd95470739e4a9d939c7c20be4ab1dd3490b77d8
